
#ifndef __CONFIG_H
#define __CONFIG_H

#include <linux/sizes.h>

#define CONFIG_SYS_SDRAM_BASE		0x1c000000
#define CONFIG_SYS_INIT_SP_ADDR		(CONFIG_SYS_SDRAM_BASE + SZ_2M)

#define CONFIG_SYS_BOOTM_LEN		SZ_64M

#define CONFIG_STANDALONE_LOAD_ADDR	0x1c200000

#define RISCV_MMODE_TIMERBASE		0xff02bff8
#define RISCV_MMODE_TIMER_FREQ		76923077

#define CONFIG_ENV_IS_NOWHERE   1 

#define CONFIG_EXTRA_ENV_SETTINGS \
    "autoload=no\0"

#define CONFIG_TIMESTAMP

#endif /* __CONFIG_H */ 
